---
- name: Install Redis 
  hosts: all
  tasks:
  - name: Install Redis Server
    become: yes
    ansible.builtin.apt:
      pkg:
      - redis-server

  - name: Ensure Redis is started
    service: name=redis-server state=started enabled=yes
    become: yes
